export const FEEDBACK_LIST_REQUEST = "FEEDBACK_LIST_REQUEST"
export const FEEDBACK_LIST_SUCCESS = "FEEDBACK_LIST_SUCCESS"
export const FEEDBACK_LIST_FAIL = "FEEDBACK_LIST_FAIL"

export const FEEDBACK_CREATE_REQUEST = "FEEDBACK_CREATE_REQUEST"
export const FEEDBACK_CREATE_SUCCESS = "FEEDBACK_CREATE_SUCCESS"
export const FEEDBACK_CREATE_FAIL = "FEEDBACK_CREATE_FAIL"


export const FEEDBACK_UPDATE_REQUEST = "FEEDBACK_UPDATE_REQUEST"
export const FEEDBACK_UPDATE_SUCCESS = "FEEDBACK_UPDATE_SUCCESS"
export const FEEDBACK_UPDATE_FAIL = "FEEDBACK_UPDATE_FAIL"


export const FEEDBACK_DELETE_REQUEST = "FEEDBACK_DELETE_REQUEST"
export const FEEDBACK_DELETE_SUCCESS = "FEEDBACK_DELETE_SUCCESS"
export const FEEDBACK_DELETE_FAIL = "FEEDBACK_DELETE_FAIL"